// Hand-written config.h for fontconfig 2.15.0, bypassing the stock
// autoconf.  x86_64 / GCC / POSIX-ish libc + freetype + libexpat in
// the sysroot.

#pragma once

#define PACKAGE                  "fontconfig"
#define PACKAGE_NAME             "fontconfig"
#define PACKAGE_VERSION          "2.15.0"
#define VERSION                  "2.15.0"
#define FC_VERSION               "2.15.0"
#define FC_ARCHITECTURE          "x86_64"

#define HAVE_STDINT_H            1
#define HAVE_STDLIB_H            1
#define HAVE_STRING_H            1
#define HAVE_SYS_TYPES_H         1
#define HAVE_SYS_STAT_H          1
#define HAVE_SYS_MMAN_H          1
#define HAVE_SYS_STATVFS_H       0
#define HAVE_FCNTL_H             1
#define HAVE_UNISTD_H            1
#define HAVE_DIRENT_H            1
#define HAVE_INTTYPES_H          1
#define HAVE_DLFCN_H             1

#define HAVE_STRCASECMP          1
#define HAVE_STRCASESTR          0
#define HAVE_STRDUP              1
#define HAVE_RAND_R              0
#define HAVE_RANDOM              0
#define HAVE_LRAND48             0
#define HAVE_RAND                1
#define HAVE_MKSTEMP             0
#define HAVE_POSIX_FADVISE       0
#define HAVE_REGEX_H             1
#define HAVE_MMAP                1
#define HAVE_GETOPT              1
#define HAVE_GETOPT_LONG         0
#define HAVE_SCANDIR             0
#define HAVE_STRUCT_STATFS_F_FSTYPENAME 0
#define HAVE_STRUCT_STATVFS_F_BASETYPE  0
#define HAVE_GETPAGESIZE         1
#define HAVE_EXPAT               1
#define HAVE_FREETYPE            1

#define STDC_HEADERS             1

#define FLEXIBLE_ARRAY_MEMBER    /* empty — C99 flex array */
#define ALIGNOF_DOUBLE           8
#define SIZEOF_VOID_P            8

// GCC is available — enables the visibility-hidden alias optimization
// in fcftalias.h/fcftaliastail.h generated by makealias.
#define HAVE_GNUC_ATTRIBUTE      1

// Locations baked into the binary.
#define CONFDIR                  "/etc/fonts"
#define CONFIGDIR                "/etc/fonts/conf.d"
#define FC_CACHEDIR              "/var/cache/fontconfig"
#define FC_DEFAULT_FONTS         "/usr/share/fonts"
#define FC_TEMPLATEDIR           "/usr/share/fontconfig/conf.avail"
#define FONTCONFIG_PATH          "/etc/fonts"

// Expat is our XML parser (libxml2 support disabled).
#define ENABLE_LIBXML2           0
#define USE_EXPAT                1

// Iconv not available — fontconfig has a fallback path.
#define HAVE_ICONV               0
