#!/usr/bin/env bash
# ── gen-meson-cross.sh — regenerate scripts/makaos-meson-cross.ini ───
#
# The meson cross file needs absolute paths (meson has no variable
# expansion in cross files), which silently breaks whenever the repo
# moves to a new checkout or machine.  Regenerate it from the actual
# repo location instead of hand-editing the paths.
#
# Idempotent and cheap; run-port-chain.sh calls it before the port
# loop, and any port script may call it defensively.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SYSROOT="${SYSROOT:-$REPO_ROOT/build/sysroot}"
TOOLCHAIN="$REPO_ROOT/toolchain"
GCC_VER="$(ls "$TOOLCHAIN/lib/gcc/x86_64-pc-makaos/" 2>/dev/null | head -1)"
GCC_VER="${GCC_VER:-14.2.0}"
OUT="$REPO_ROOT/scripts/makaos-meson-cross.ini"

cat > "$OUT" <<EOF
# MakaOS meson cross-compile file — GENERATED by scripts/gen-meson-cross.sh.
# Do not hand-edit paths; re-run the generator after moving the repo.
# Pkg-config sysroot is set via PKG_CONFIG_* env vars at invocation time
# because meson's built-in sys_root handling collides with our sysroot
# being mutable across builds.

[binaries]
c        = '$TOOLCHAIN/bin/x86_64-pc-makaos-gcc'
cpp      = '$TOOLCHAIN/bin/x86_64-pc-makaos-g++'
ar       = '$TOOLCHAIN/bin/x86_64-pc-makaos-ar'
strip    = '$TOOLCHAIN/bin/x86_64-pc-makaos-strip'
pkg-config = 'pkg-config'

[host_machine]
system     = 'makaos'
cpu_family = 'x86_64'
cpu        = 'x86_64'
endian     = 'little'

[properties]
needs_exe_wrapper = true
sys_root          = '$SYSROOT'

[built-in options]
c_args      = ['--sysroot=$SYSROOT', '-nostdinc', '-I$SYSROOT/usr/include', '-I$TOOLCHAIN/lib/gcc/x86_64-pc-makaos/$GCC_VER/include', '-D__STDC_ISO_10646__=201706L']
cpp_args    = ['--sysroot=$SYSROOT', '-nostdinc', '-I$SYSROOT/usr/include', '-I$TOOLCHAIN/lib/gcc/x86_64-pc-makaos/$GCC_VER/include', '-D__STDC_ISO_10646__=201706L']
c_link_args = ['--sysroot=$SYSROOT', '-specs=$REPO_ROOT/scripts/makaos-gcc-specs']
cpp_link_args = ['--sysroot=$SYSROOT', '-specs=$REPO_ROOT/scripts/makaos-gcc-specs']
EOF

echo "[gen-meson-cross] wrote $OUT (repo=$REPO_ROOT)"
