#!/usr/bin/env bash
# ── MakaOS json-c port ─────────────────────────────────────────────────
#
# sway uses json-c for its IPC message format.  ~6 KLOC of C, no deps
# beyond libc.  Bypass json-c's cmake build — compile the .c files
# directly with our cross-gcc.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JSONC_VERSION="0.18"
JSONC_URL="https://s3.amazonaws.com/json-c_releases/releases/json-c-${JSONC_VERSION}.tar.gz"

BUILD_DIR="$REPO_ROOT/build"
THIRD_PARTY="$BUILD_DIR/third_party"
JSONC_SRC="$THIRD_PARTY/json-c-${JSONC_VERSION}"
JSONC_TARBALL="$THIRD_PARTY/json-c-${JSONC_VERSION}.tar.gz"

SYSROOT="${SYSROOT:-$BUILD_DIR/sysroot}"

CROSS_CC="$REPO_ROOT/toolchain/bin/x86_64-pc-makaos-gcc"
CROSS_AR="$REPO_ROOT/toolchain/bin/x86_64-pc-makaos-ar"

log() { printf '[port-jsonc] %s\n' "$*" >&2; }

fetch() {
    mkdir -p "$THIRD_PARTY"
    if [ ! -f "$JSONC_TARBALL" ]; then
        log "downloading json-c ${JSONC_VERSION}"
        curl -fsSL -o "$JSONC_TARBALL" "$JSONC_URL"
    fi
    if [ ! -d "$JSONC_SRC" ]; then
        log "extracting"
        tar -xzf "$JSONC_TARBALL" -C "$THIRD_PARTY"
    fi
}

write_config_h() {
    # Expand json.h.cmakein (the umbrella header) — @JSON_H_*@ placeholders
    # resolve to `#include "json_{patch,pointer}.h"` since we include those.
    sed -e 's|@JSON_H_JSON_PATCH@|#include "json_patch.h"|' \
        -e 's|@JSON_H_JSON_POINTER@|#include "json_pointer.h"|' \
        "$JSONC_SRC/json.h.cmakein" > "$JSONC_SRC/json.h"

    # config.h is normally generated by cmake from a cmake-config template.
    # Everything json-c probes for is POSIX-standard and we have it.
    cat > "$JSONC_SRC/config.h" <<'CFG'
#pragma once
#define HAVE_STDARG_H     1
#define HAVE_STDINT_H     1
#define HAVE_STDLIB_H     1
#define HAVE_STRING_H     1
#define HAVE_STRINGS_H    1
#define HAVE_UNISTD_H     1
#define HAVE_SYS_TYPES_H  1
#define HAVE_FCNTL_H      1
#define HAVE_INTTYPES_H   1
#define HAVE_LIMITS_H     1
/* HAVE_SYS_RANDOM_H / HAVE_ENDIAN_H / HAVE_SYSLOG_H / HAVE_GETRANDOM
 * all intentionally left undefined — json-c uses #ifdef not #if. */
#define HAVE_STRTOLL      1
#define HAVE_STRTOULL     1
#define HAVE_ATOMIC_BUILTINS 1
#define JSON_C_HAVE_INTTYPES_H 1
#define JSON_C_HAVE_STDARG_H   1
#define STDC_HEADERS           1
#define SIZEOF_SIZE_T          8
#define SIZEOF_SSIZE_T         8
#define SIZEOF_LONG            8
#define SIZEOF_INT             4
#define SIZEOF_LONG_LONG       8
#define SIZEOF_INT64_T         8
#define HAVE_SNPRINTF          1
#define HAVE_VSNPRINTF         1
#define HAVE_VASPRINTF         1
#define HAVE_VPRINTF           1
#define HAVE_STRDUP            1
#define HAVE_STRNDUP           1
#define HAVE_STRNCASECMP       1
#define HAVE_STRERROR          1
/* HAVE_USELOCALE undefined — we have the symbol but newlocale/uselocale
 * are stubs on MakaOS (single-locale system).  Forcing json-c to use
 * locale-swapping for its numeric parse buys us nothing.  */
#define SSIZE_T_MAX            0x7FFFFFFFFFFFFFFFLL
CFG
    cat > "$JSONC_SRC/json_config.h" <<'CFG'
#pragma once
#define JSON_C_HAVE_INTTYPES_H 1
#define JSON_C_HAVE_STDARG_H   1
CFG
}

build_lib() {
    local objdir="$BUILD_DIR/jsonc_objs"
    mkdir -p "$objdir"

    write_config_h

    local cflags=(
        -O2 -fPIC -std=gnu11
        -Wall
        -Wno-unused-parameter
        -Wno-unused-function
        -Wno-missing-field-initializers
        -Wno-implicit-function-declaration
        -Wno-deprecated-declarations
        -DHAVE_CONFIG_H
        -I "$JSONC_SRC"
        --sysroot="$SYSROOT"
        -nostdinc
        -isystem "$SYSROOT/usr/include"
    )

    local srcs=(
        arraylist.c
        debug.c
        json_c_version.c
        json_object.c
        json_object_iterator.c
        json_patch.c
        json_pointer.c
        json_tokener.c
        json_util.c
        json_visit.c
        linkhash.c
        printbuf.c
        random_seed.c
        strerror_override.c
    )

    local objs=()
    for src in "${srcs[@]}"; do
        local o="$objdir/${src%.c}.o"
        objs+=("$o")
        if [ "$JSONC_SRC/$src" -nt "$o" ]; then
            "$CROSS_CC" "${cflags[@]}" -c "$JSONC_SRC/$src" -o "$o"
        fi
    done

    rm -f "$SYSROOT/usr/lib/libjson-c.a"
    "$CROSS_AR" rcs "$SYSROOT/usr/lib/libjson-c.a" "${objs[@]}"
    log "libjson-c.a: $(stat -c%s "$SYSROOT/usr/lib/libjson-c.a") bytes"
}

install_headers() {
    mkdir -p "$SYSROOT/usr/include/json-c"
    for h in "$JSONC_SRC"/*.h; do
        cp "$h" "$SYSROOT/usr/include/json-c/"
    done
    cp "$JSONC_SRC/json_config.h" "$SYSROOT/usr/include/json-c/"
    log "installed $(ls "$SYSROOT/usr/include/json-c/" | wc -l) headers"
}

install_pc() {
    mkdir -p "$SYSROOT/usr/lib/pkgconfig"
    cat > "$SYSROOT/usr/lib/pkgconfig/json-c.pc" <<EOF
prefix=/usr
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: json-c
Description: JSON implementation in C
Version: ${JSONC_VERSION}
Libs: -L\${libdir} -ljson-c
Cflags: -I\${includedir}/json-c -I\${includedir}
EOF
}

main() {
    [ "${FORCE:-0}" = "1" ] && rm -rf "$BUILD_DIR/jsonc_objs" "$SYSROOT/usr/lib/libjson-c.a"
    fetch
    build_lib
    install_headers
    install_pc
    log "done"
}

main "$@"
