#pragma once
#include "common.h"

/* ── Stack walker — DEBUGGING.md §5 ───────────────────────────────────
 *
 * Frame-pointer fast path (§5.1): follow the %rbp chain, reading
 * [rbp]  → previous frame pointer
 * [rbp+8] → return address
 * Stops on NULL, unreadable address, or after 128 frames.
 *
 * The kernel is compiled with -fno-omit-frame-pointer (see build.sh /
 * KERNEL_CFLAGS), so every kernel C frame participates.  ASM
 * trampolines that don't maintain rbp break the chain; the walker
 * prints `???` for the broken frame and keeps going.
 *
 * Symbolization (§5.3): each return address is looked up against a
 * sorted table of (addr, name) entries compiled into the kernel by
 * build.sh's two-pass link.  A raw RIP with no matching symbol prints
 * as `0x<hex>` so offline tooling (addr2line, nm) can resolve it.
 *
 * Safe from any context — panic, IRQ, ISR.  No heap, no locks.
 */

typedef struct {
    uint64_t    addr;
    const char* name;
} ksym_entry_t;

/* Generated by build.sh.  Sorted by address ascending. */
extern const ksym_entry_t g_ksyms[];
extern const size_t       g_ksyms_count;

/* Look up the symbol whose range covers `rip`.  Fills *out_offset
 * with rip - symbol.addr.  Returns NULL if no symbol covers rip
 * (e.g., because it lives outside the kernel image). */
const char* ksym_lookup(uint64_t rip, uint64_t* out_offset);

/* Walk the current frame's caller chain and emit each frame to serial
 * in the canonical format:
 *
 *   #N 0xRRRRRRRRRRRRRRRR <func+0xoff>
 *
 * Runs unlocked — caller must already hold the serial lock or be in
 * the panic path with other CPUs halted.  Stops on NULL, unreadable
 * rbp, mismatched return-address plausibility check, or after 128
 * frames. */
void stackwalk_print(uint64_t rbp);

/* Variant that starts from an explicit (rbp, rip) pair — used by
 * panic_from_exception() to walk from the saved interrupt frame
 * rather than the panic handler's own frame. */
void stackwalk_print_from(uint64_t rbp, uint64_t rip);

/* Read this CPU's current %rbp.  Inline so the calling frame itself
 * is the starting point. */
static inline uint64_t read_rbp(void) {
    uint64_t rbp;
    __asm__ volatile ("mov %%rbp, %0" : "=r"(rbp));
    return rbp;
}
